{% set name = "pytest-tldr" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43f43fe758569df620c433a79d3cbee698e77268efebbc6e22ce1e66095a0881

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
    - pytest >=3.5.0
  run:
    - python >={{ python_min }}
    - pytest >=3.5.0
test:
  imports:
    - pytest_tldr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/freakboy3742/pytest-tldr
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pytest plugin that limits the output to just the things you need.
  dev_url: https://github.com/freakboy3742/pytest-tldr

extra:
  recipe-maintainers:
    - philip-khor
