{% set name = "pytest-tldr" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5c0ccc6991276c8489ff1720f1498d5130690bb8504aaf8c7bd115bf91abc035

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest >=7.0.0
    - setuptools 80.9.0
    - setuptools_scm 9.2.2
  run:
    - python >={{ python_min }}
    - pytest >=7.0.0
test:
  imports:
    - pytest_tldr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/freakboy3742/pytest-tldr
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pytest plugin that limits the output to just the things you need.
  dev_url: https://github.com/freakboy3742/pytest-tldr

extra:
  recipe-maintainers:
    - philip-khor
