{% set name = "pytest-tldr" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7bb9dfb7869d61f6c6f80da37178c308e084badbce5e00ab2aabe5b8fef2e9c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - pytest >=3.5.0
  run:
    - python
    - pytest >=3.5.0
test:
  imports:
    - pytest_tldr
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/freakboy3742/pytest-tldr
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pytest plugin that limits the output to just the things you need.
  dev_url: https://github.com/freakboy3742/pytest-tldr

extra:
  recipe-maintainers:
    - philip-khor
